# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/artem/projects/github/vlasov-solver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/artem/projects/github/vlasov-solver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artem/projects/github/vlasov-solver/CMakeFiles /home/artem/projects/github/vlasov-solver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artem/projects/github/vlasov-solver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fdtd

# Build rule for target.
fdtd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fdtd
.PHONY : fdtd

# fast build rule for target.
fdtd/fast:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/build
.PHONY : fdtd/fast

#=============================================================================
# Target rules for targets named file_saving

# Build rule for target.
file_saving: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file_saving
.PHONY : file_saving

# fast build rule for target.
file_saving/fast:
	$(MAKE) -f CMakeFiles/file_saving.dir/build.make CMakeFiles/file_saving.dir/build
.PHONY : file_saving/fast

#=============================================================================
# Target rules for targets named mesh

# Build rule for target.
mesh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mesh
.PHONY : mesh

# fast build rule for target.
mesh/fast:
	$(MAKE) -f CMakeFiles/mesh.dir/build.make CMakeFiles/mesh.dir/build
.PHONY : mesh/fast

#=============================================================================
# Target rules for targets named mymath

# Build rule for target.
mymath: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mymath
.PHONY : mymath

# fast build rule for target.
mymath/fast:
	$(MAKE) -f CMakeFiles/mymath.dir/build.make CMakeFiles/mymath.dir/build
.PHONY : mymath/fast

#=============================================================================
# Target rules for targets named output

# Build rule for target.
output: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output
.PHONY : output

# fast build rule for target.
output/fast:
	$(MAKE) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/build
.PHONY : output/fast

#=============================================================================
# Target rules for targets named particle

# Build rule for target.
particle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particle
.PHONY : particle

# fast build rule for target.
particle/fast:
	$(MAKE) -f CMakeFiles/particle.dir/build.make CMakeFiles/particle.dir/build
.PHONY : particle/fast

#=============================================================================
# Target rules for targets named pfc

# Build rule for target.
pfc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfc
.PHONY : pfc

# fast build rule for target.
pfc/fast:
	$(MAKE) -f CMakeFiles/pfc.dir/build.make CMakeFiles/pfc.dir/build
.PHONY : pfc/fast

#=============================================================================
# Target rules for targets named pfunc

# Build rule for target.
pfunc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pfunc
.PHONY : pfunc

# fast build rule for target.
pfunc/fast:
	$(MAKE) -f CMakeFiles/pfunc.dir/build.make CMakeFiles/pfunc.dir/build
.PHONY : pfunc/fast

#=============================================================================
# Target rules for targets named plasmas

# Build rule for target.
plasmas: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 plasmas
.PHONY : plasmas

# fast build rule for target.
plasmas/fast:
	$(MAKE) -f CMakeFiles/plasmas.dir/build.make CMakeFiles/plasmas.dir/build
.PHONY : plasmas/fast

#=============================================================================
# Target rules for targets named pyinput

# Build rule for target.
pyinput: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pyinput
.PHONY : pyinput

# fast build rule for target.
pyinput/fast:
	$(MAKE) -f CMakeFiles/pyinput.dir/build.make CMakeFiles/pyinput.dir/build
.PHONY : pyinput/fast

#=============================================================================
# Target rules for targets named solver

# Build rule for target.
solver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solver
.PHONY : solver

# fast build rule for target.
solver/fast:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/build
.PHONY : solver/fast

#=============================================================================
# Target rules for targets named testparticles

# Build rule for target.
testparticles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testparticles
.PHONY : testparticles

# fast build rule for target.
testparticles/fast:
	$(MAKE) -f CMakeFiles/testparticles.dir/build.make CMakeFiles/testparticles.dir/build
.PHONY : testparticles/fast

#=============================================================================
# Target rules for targets named vlasov

# Build rule for target.
vlasov: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vlasov
.PHONY : vlasov

# fast build rule for target.
vlasov/fast:
	$(MAKE) -f CMakeFiles/vlasov.dir/build.make CMakeFiles/vlasov.dir/build
.PHONY : vlasov/fast

src/fdtd.o: src/fdtd.cpp.o
.PHONY : src/fdtd.o

# target to build an object file
src/fdtd.cpp.o:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/fdtd.cpp.o
.PHONY : src/fdtd.cpp.o

src/fdtd.i: src/fdtd.cpp.i
.PHONY : src/fdtd.i

# target to preprocess a source file
src/fdtd.cpp.i:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/fdtd.cpp.i
.PHONY : src/fdtd.cpp.i

src/fdtd.s: src/fdtd.cpp.s
.PHONY : src/fdtd.s

# target to generate assembly for a file
src/fdtd.cpp.s:
	$(MAKE) -f CMakeFiles/fdtd.dir/build.make CMakeFiles/fdtd.dir/src/fdtd.cpp.s
.PHONY : src/fdtd.cpp.s

src/file_saving.o: src/file_saving.cpp.o
.PHONY : src/file_saving.o

# target to build an object file
src/file_saving.cpp.o:
	$(MAKE) -f CMakeFiles/file_saving.dir/build.make CMakeFiles/file_saving.dir/src/file_saving.cpp.o
.PHONY : src/file_saving.cpp.o

src/file_saving.i: src/file_saving.cpp.i
.PHONY : src/file_saving.i

# target to preprocess a source file
src/file_saving.cpp.i:
	$(MAKE) -f CMakeFiles/file_saving.dir/build.make CMakeFiles/file_saving.dir/src/file_saving.cpp.i
.PHONY : src/file_saving.cpp.i

src/file_saving.s: src/file_saving.cpp.s
.PHONY : src/file_saving.s

# target to generate assembly for a file
src/file_saving.cpp.s:
	$(MAKE) -f CMakeFiles/file_saving.dir/build.make CMakeFiles/file_saving.dir/src/file_saving.cpp.s
.PHONY : src/file_saving.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/vlasov.dir/build.make CMakeFiles/vlasov.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/vlasov.dir/build.make CMakeFiles/vlasov.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/vlasov.dir/build.make CMakeFiles/vlasov.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mesh.o: src/mesh.cpp.o
.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/mesh.dir/build.make CMakeFiles/mesh.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i
.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/mesh.dir/build.make CMakeFiles/mesh.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s
.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/mesh.dir/build.make CMakeFiles/mesh.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/mymath.o: src/mymath.cpp.o
.PHONY : src/mymath.o

# target to build an object file
src/mymath.cpp.o:
	$(MAKE) -f CMakeFiles/mymath.dir/build.make CMakeFiles/mymath.dir/src/mymath.cpp.o
.PHONY : src/mymath.cpp.o

src/mymath.i: src/mymath.cpp.i
.PHONY : src/mymath.i

# target to preprocess a source file
src/mymath.cpp.i:
	$(MAKE) -f CMakeFiles/mymath.dir/build.make CMakeFiles/mymath.dir/src/mymath.cpp.i
.PHONY : src/mymath.cpp.i

src/mymath.s: src/mymath.cpp.s
.PHONY : src/mymath.s

# target to generate assembly for a file
src/mymath.cpp.s:
	$(MAKE) -f CMakeFiles/mymath.dir/build.make CMakeFiles/mymath.dir/src/mymath.cpp.s
.PHONY : src/mymath.cpp.s

src/output.o: src/output.cpp.o
.PHONY : src/output.o

# target to build an object file
src/output.cpp.o:
	$(MAKE) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/output.cpp.o
.PHONY : src/output.cpp.o

src/output.i: src/output.cpp.i
.PHONY : src/output.i

# target to preprocess a source file
src/output.cpp.i:
	$(MAKE) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/output.cpp.i
.PHONY : src/output.cpp.i

src/output.s: src/output.cpp.s
.PHONY : src/output.s

# target to generate assembly for a file
src/output.cpp.s:
	$(MAKE) -f CMakeFiles/output.dir/build.make CMakeFiles/output.dir/src/output.cpp.s
.PHONY : src/output.cpp.s

src/particle.o: src/particle.cpp.o
.PHONY : src/particle.o

# target to build an object file
src/particle.cpp.o:
	$(MAKE) -f CMakeFiles/particle.dir/build.make CMakeFiles/particle.dir/src/particle.cpp.o
.PHONY : src/particle.cpp.o

src/particle.i: src/particle.cpp.i
.PHONY : src/particle.i

# target to preprocess a source file
src/particle.cpp.i:
	$(MAKE) -f CMakeFiles/particle.dir/build.make CMakeFiles/particle.dir/src/particle.cpp.i
.PHONY : src/particle.cpp.i

src/particle.s: src/particle.cpp.s
.PHONY : src/particle.s

# target to generate assembly for a file
src/particle.cpp.s:
	$(MAKE) -f CMakeFiles/particle.dir/build.make CMakeFiles/particle.dir/src/particle.cpp.s
.PHONY : src/particle.cpp.s

src/pfc.o: src/pfc.cpp.o
.PHONY : src/pfc.o

# target to build an object file
src/pfc.cpp.o:
	$(MAKE) -f CMakeFiles/pfc.dir/build.make CMakeFiles/pfc.dir/src/pfc.cpp.o
.PHONY : src/pfc.cpp.o

src/pfc.i: src/pfc.cpp.i
.PHONY : src/pfc.i

# target to preprocess a source file
src/pfc.cpp.i:
	$(MAKE) -f CMakeFiles/pfc.dir/build.make CMakeFiles/pfc.dir/src/pfc.cpp.i
.PHONY : src/pfc.cpp.i

src/pfc.s: src/pfc.cpp.s
.PHONY : src/pfc.s

# target to generate assembly for a file
src/pfc.cpp.s:
	$(MAKE) -f CMakeFiles/pfc.dir/build.make CMakeFiles/pfc.dir/src/pfc.cpp.s
.PHONY : src/pfc.cpp.s

src/pfunc.o: src/pfunc.cpp.o
.PHONY : src/pfunc.o

# target to build an object file
src/pfunc.cpp.o:
	$(MAKE) -f CMakeFiles/pfunc.dir/build.make CMakeFiles/pfunc.dir/src/pfunc.cpp.o
.PHONY : src/pfunc.cpp.o

src/pfunc.i: src/pfunc.cpp.i
.PHONY : src/pfunc.i

# target to preprocess a source file
src/pfunc.cpp.i:
	$(MAKE) -f CMakeFiles/pfunc.dir/build.make CMakeFiles/pfunc.dir/src/pfunc.cpp.i
.PHONY : src/pfunc.cpp.i

src/pfunc.s: src/pfunc.cpp.s
.PHONY : src/pfunc.s

# target to generate assembly for a file
src/pfunc.cpp.s:
	$(MAKE) -f CMakeFiles/pfunc.dir/build.make CMakeFiles/pfunc.dir/src/pfunc.cpp.s
.PHONY : src/pfunc.cpp.s

src/plasmas.o: src/plasmas.cpp.o
.PHONY : src/plasmas.o

# target to build an object file
src/plasmas.cpp.o:
	$(MAKE) -f CMakeFiles/plasmas.dir/build.make CMakeFiles/plasmas.dir/src/plasmas.cpp.o
.PHONY : src/plasmas.cpp.o

src/plasmas.i: src/plasmas.cpp.i
.PHONY : src/plasmas.i

# target to preprocess a source file
src/plasmas.cpp.i:
	$(MAKE) -f CMakeFiles/plasmas.dir/build.make CMakeFiles/plasmas.dir/src/plasmas.cpp.i
.PHONY : src/plasmas.cpp.i

src/plasmas.s: src/plasmas.cpp.s
.PHONY : src/plasmas.s

# target to generate assembly for a file
src/plasmas.cpp.s:
	$(MAKE) -f CMakeFiles/plasmas.dir/build.make CMakeFiles/plasmas.dir/src/plasmas.cpp.s
.PHONY : src/plasmas.cpp.s

src/pyinput.o: src/pyinput.cpp.o
.PHONY : src/pyinput.o

# target to build an object file
src/pyinput.cpp.o:
	$(MAKE) -f CMakeFiles/pyinput.dir/build.make CMakeFiles/pyinput.dir/src/pyinput.cpp.o
.PHONY : src/pyinput.cpp.o

src/pyinput.i: src/pyinput.cpp.i
.PHONY : src/pyinput.i

# target to preprocess a source file
src/pyinput.cpp.i:
	$(MAKE) -f CMakeFiles/pyinput.dir/build.make CMakeFiles/pyinput.dir/src/pyinput.cpp.i
.PHONY : src/pyinput.cpp.i

src/pyinput.s: src/pyinput.cpp.s
.PHONY : src/pyinput.s

# target to generate assembly for a file
src/pyinput.cpp.s:
	$(MAKE) -f CMakeFiles/pyinput.dir/build.make CMakeFiles/pyinput.dir/src/pyinput.cpp.s
.PHONY : src/pyinput.cpp.s

src/solver.o: src/solver.cpp.o
.PHONY : src/solver.o

# target to build an object file
src/solver.cpp.o:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/solver.cpp.o
.PHONY : src/solver.cpp.o

src/solver.i: src/solver.cpp.i
.PHONY : src/solver.i

# target to preprocess a source file
src/solver.cpp.i:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/solver.cpp.i
.PHONY : src/solver.cpp.i

src/solver.s: src/solver.cpp.s
.PHONY : src/solver.s

# target to generate assembly for a file
src/solver.cpp.s:
	$(MAKE) -f CMakeFiles/solver.dir/build.make CMakeFiles/solver.dir/src/solver.cpp.s
.PHONY : src/solver.cpp.s

src/testparticles.o: src/testparticles.cpp.o
.PHONY : src/testparticles.o

# target to build an object file
src/testparticles.cpp.o:
	$(MAKE) -f CMakeFiles/testparticles.dir/build.make CMakeFiles/testparticles.dir/src/testparticles.cpp.o
.PHONY : src/testparticles.cpp.o

src/testparticles.i: src/testparticles.cpp.i
.PHONY : src/testparticles.i

# target to preprocess a source file
src/testparticles.cpp.i:
	$(MAKE) -f CMakeFiles/testparticles.dir/build.make CMakeFiles/testparticles.dir/src/testparticles.cpp.i
.PHONY : src/testparticles.cpp.i

src/testparticles.s: src/testparticles.cpp.s
.PHONY : src/testparticles.s

# target to generate assembly for a file
src/testparticles.cpp.s:
	$(MAKE) -f CMakeFiles/testparticles.dir/build.make CMakeFiles/testparticles.dir/src/testparticles.cpp.s
.PHONY : src/testparticles.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... fdtd"
	@echo "... file_saving"
	@echo "... mesh"
	@echo "... mymath"
	@echo "... output"
	@echo "... particle"
	@echo "... pfc"
	@echo "... pfunc"
	@echo "... plasmas"
	@echo "... pyinput"
	@echo "... rebuild_cache"
	@echo "... solver"
	@echo "... testparticles"
	@echo "... vlasov"
	@echo "... src/fdtd.o"
	@echo "... src/fdtd.i"
	@echo "... src/fdtd.s"
	@echo "... src/file_saving.o"
	@echo "... src/file_saving.i"
	@echo "... src/file_saving.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/mymath.o"
	@echo "... src/mymath.i"
	@echo "... src/mymath.s"
	@echo "... src/output.o"
	@echo "... src/output.i"
	@echo "... src/output.s"
	@echo "... src/particle.o"
	@echo "... src/particle.i"
	@echo "... src/particle.s"
	@echo "... src/pfc.o"
	@echo "... src/pfc.i"
	@echo "... src/pfc.s"
	@echo "... src/pfunc.o"
	@echo "... src/pfunc.i"
	@echo "... src/pfunc.s"
	@echo "... src/plasmas.o"
	@echo "... src/plasmas.i"
	@echo "... src/plasmas.s"
	@echo "... src/pyinput.o"
	@echo "... src/pyinput.i"
	@echo "... src/pyinput.s"
	@echo "... src/solver.o"
	@echo "... src/solver.i"
	@echo "... src/solver.s"
	@echo "... src/testparticles.o"
	@echo "... src/testparticles.i"
	@echo "... src/testparticles.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

